Create reverse_ll_kgroups.cpp
maheshjainckd/Hacktoberfest2022-for-everyone pull request #156
Opened 2022-09-30 18:45 UTC by TanishqKhetan

2022-09-30 21:05 UTC, TanishqKhetan commented
could you please see to this code

2022-10-01 09:00 UTC, dikshantrajput requested changes

2022-10-01 09:00 UTC, dikshantrajput commented on CPP/reverse_ll_kgroups.cpp
> +Love Babbar Adding codes for previous Lectures
Please remove all these stuffs from top and bottom

2022-10-01 11:40 UTC, TanishqKhetan reviewed
I have updated the code kindly review it

2022-10-01 11:40 UTC, TanishqKhetan commented
updated

2022-10-01 11:49 UTC, dikshantrajput commented
Have you added your name in the contributors.html file?

2022-10-01 11:59 UTC, TanishqKhetan commented
No I have contributed to c++

On Sat, 1 Oct, 2022, 5:19 pm dikshant rajput, ***@***.***>
wrote:

> Have you added your name in the contributors.html file?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/maheshjainckd/Hacktoberfest2022-for-everyone/pull/156#issuecomment-1264339625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMUUVES7TIEL3Z77QHM4F5DWBAQNXANCNFSM6AAAAAAQ2AO55Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-10-01 13:01 UTC, dikshantrajput commented
Please add your name also to the contributors.html file

2022-10-05 10:07 UTC, merged